# Generated by Django 5.0.4 on 2024-06-17 05:00

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=20)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(default='+55', max_length=128, region='BR')),
                ('email', models.EmailField(max_length=254)),
                ('nivel', models.CharField(choices=[('adm_sistema', 'Administrador do Sistema'), ('adm', 'Administrador do Setor'), ('funcionario', 'Funcionário')], max_length=25)),
                ('status', models.BooleanField(default=True)),
                ('setor', models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.CASCADE, to='home.setor')),
            ],
        ),
        migrations.CreateModel(
            name='Chamados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=280)),
                ('status', models.BooleanField(default=True)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_limite', models.DateTimeField()),
                ('funcionario_abre', models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.CASCADE, to='home.funcionario')),
                ('setor', models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.CASCADE, to='home.setor')),
            ],
        ),
    ]
